### ISSUE TITLE
It's great! But I think zig officials should create a similar central warehouse.

### ISSUE THREAD

**Issue by HongChenLuYuan** [RohanVashisht1234/zigistry#21]
It's great! But I think zig officials should create a similar central warehouse.

**Comment by RohanVashisht1234** [comment]
Thanks a lot, but Zig officials don't quite support the idea of a centralised server, I have built this as one so that people who need a centralised server for easy access, uploads and information can use [Zigistry](https://zigistry.dev). Also, you can check out [this statement](https://github.com/ziglang/zig/blob/master/.github/CODE_OF_CONDUCT.md?plain=1#L8-L9) written in [Zig's code of conduct](https://github.com/ziglang/zig/blob/master/.github/CODE_OF_CONDUCT.md) which states that _"There is no concept of "official" or "unofficial", however, each
gathering place has its own moderators and rules."_, and [Zigistry follows the same code of conduct](https://github.com/RohanVashisht1234/zigistry/blob/main/.github/code_of_conduct.md) as mentioned there, also, that's the reason why I like Zig community so much. No concept of "official" or "unofficial".
